import express from 'express';
import { authMiddleware } from '../middleware/auth.js';
import pool from '../database/db.js';

const router = express.Router();
router.use(authMiddleware);

// ============ Action Sessions ============

// Create action session
router.post('/sessions', async (req, res) => {
  try {
    const { sessionId, sessionName, autoGeneratedName, autoGeneratedBy, startTime, endTime, duration, actionCount, screenshotCount, actions, metadata } = req.body;
    
    const result = await pool.query(
      `INSERT INTO action_sessions 
       (user_id, session_id, session_name, auto_generated_name, auto_generated_by, start_time, end_time, duration, action_count, screenshot_count, actions, metadata)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
       RETURNING *`,
      [req.userId, sessionId, sessionName, autoGeneratedName, autoGeneratedBy, new Date(startTime), new Date(endTime), duration, actionCount, screenshotCount, JSON.stringify(actions), JSON.stringify(metadata || {})]
    );
    
    res.status(201).json(result.rows[0]);
  } catch (error) {
    console.error('Create session error:', error);
    res.status(500).json({ error: 'Failed to create action session' });
  }
});

// Get user sessions
router.get('/sessions', async (req, res) => {
  try {
    const { limit = 50, offset = 0 } = req.query;
    const result = await pool.query(
      `SELECT * FROM action_sessions 
       WHERE user_id = $1 
       ORDER BY start_time DESC 
       LIMIT $2 OFFSET $3`,
      [req.userId, parseInt(limit), parseInt(offset)]
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Get sessions error:', error);
    res.status(500).json({ error: 'Failed to get sessions' });
  }
});

// Get session by ID
router.get('/sessions/:id', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM action_sessions WHERE session_id = $1 AND user_id = $2',
      [req.params.id, req.userId]
    );
    
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Session not found' });
    }
    
    res.json(result.rows[0]);
  } catch (error) {
    console.error('Get session error:', error);
    res.status(500).json({ error: 'Failed to get session' });
  }
});

// Delete session
router.delete('/sessions/:id', async (req, res) => {
  try {
    await pool.query(
      'DELETE FROM action_sessions WHERE session_id = $1 AND user_id = $2',
      [req.params.id, req.userId]
    );
    res.json({ success: true });
  } catch (error) {
    console.error('Delete session error:', error);
    res.status(500).json({ error: 'Failed to delete session' });
  }
});

// ============ Automation Tasks ============

// Create/update task
router.post('/tasks/:id', async (req, res) => {
  try {
    const { id, name, type, actions, schedule, interval, enabled, metadata } = req.body;
    
    const result = await pool.query(
      `INSERT INTO automation_tasks 
       (user_id, task_id, name, type, actions, schedule, interval, enabled, metadata)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
       ON CONFLICT (user_id, task_id) 
       DO UPDATE SET name = $3, type = $4, actions = $5, schedule = $6, interval = $7, enabled = $8, metadata = $9
       RETURNING *`,
      [req.userId, id, name, type, JSON.stringify(actions), schedule, interval, enabled, JSON.stringify(metadata || {})]
    );
    
    res.json(result.rows[0]);
  } catch (error) {
    console.error('Save task error:', error);
    res.status(500).json({ error: 'Failed to save task' });
  }
});

// Get user tasks
router.get('/tasks', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM automation_tasks WHERE user_id = $1 ORDER BY created_at DESC',
      [req.userId]
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Get tasks error:', error);
    res.status(500).json({ error: 'Failed to get tasks' });
  }
});

// Delete task
router.delete('/tasks/:id', async (req, res) => {
  try {
    await pool.query(
      'DELETE FROM automation_tasks WHERE task_id = $1 AND user_id = $2',
      [req.params.id, req.userId]
    );
    res.json({ success: true });
  } catch (error) {
    console.error('Delete task error:', error);
    res.status(500).json({ error: 'Failed to delete task' });
  }
});

// ============ Automation Rules ============

// Create/update rule
router.post('/rules/:id', async (req, res) => {
  try {
    const { id, name, trigger, conditions, actions, enabled } = req.body;
    
    const result = await pool.query(
      `INSERT INTO automation_rules 
       (user_id, rule_id, name, trigger, conditions, actions, enabled)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       ON CONFLICT (user_id, rule_id) 
       DO UPDATE SET name = $3, trigger = $4, conditions = $5, actions = $6, enabled = $7
       RETURNING *`,
      [req.userId, id, name, JSON.stringify(trigger), JSON.stringify(conditions), JSON.stringify(actions), enabled]
    );
    
    res.json(result.rows[0]);
  } catch (error) {
    console.error('Save rule error:', error);
    res.status(500).json({ error: 'Failed to save rule' });
  }
});

// Get user rules
router.get('/rules', async (req, res) => {
  try {
    const result = await pool.query(
      'SELECT * FROM automation_rules WHERE user_id = $1 ORDER BY created_at DESC',
      [req.userId]
    );
    res.json(result.rows);
  } catch (error) {
    console.error('Get rules error:', error);
    res.status(500).json({ error: 'Failed to get rules' });
  }
});

// Delete rule
router.delete('/rules/:id', async (req, res) => {
  try {
    await pool.query(
      'DELETE FROM automation_rules WHERE rule_id = $1 AND user_id = $2',
      [req.params.id, req.userId]
    );
    res.json({ success: true });
  } catch (error) {
    console.error('Delete rule error:', error);
    res.status(500).json({ error: 'Failed to delete rule' });
  }
});

// ============ LLM Processed Actions ============

// Store LLM-processed action
router.post('/llm-actions', async (req, res) => {
  try {
    const { sessionId, actionData, llmResponse, tags } = req.body;
    
    const result = await pool.query(
      `INSERT INTO llm_processed_actions 
       (user_id, session_id, action_data, llm_response, tags)
       VALUES ($1, $2, $3, $4, $5)
       RETURNING *`,
      [req.userId, sessionId, JSON.stringify(actionData), JSON.stringify(llmResponse), JSON.stringify(tags || [])]
    );
    
    res.status(201).json(result.rows[0]);
  } catch (error) {
    console.error('Store LLM action error:', error);
    res.status(500).json({ error: 'Failed to store LLM action' });
  }
});

// Search LLM actions by tags
router.post('/llm-actions/search', async (req, res) => {
  try {
    const { tags, limit = 100 } = req.body;
    
    const result = await pool.query(
      `SELECT * FROM llm_processed_actions 
       WHERE user_id = $1 AND tags && $2
       ORDER BY created_at DESC
       LIMIT $3`,
      [req.userId, tags, parseInt(limit)]
    );
    
    res.json(result.rows);
  } catch (error) {
    console.error('Search LLM actions error:', error);
    res.status(500).json({ error: 'Failed to search LLM actions' });
  }
});

// Get LLM actions for RAG
router.get('/llm-actions/rag', async (req, res) => {
  try {
    const { query, limit = 50 } = req.query;
    
    // Simple text search (for production, use pgvector)
    const result = await pool.query(
      `SELECT * FROM llm_processed_actions 
       WHERE user_id = $1 
       AND (action_data::text ILIKE $2 OR llm_response::text ILIKE $2)
       ORDER BY created_at DESC
       LIMIT $3`,
      [req.userId, `%${query}%`, parseInt(limit)]
    );
    
    res.json(result.rows);
  } catch (error) {
    console.error('Get RAG actions error:', error);
    res.status(500).json({ error: 'Failed to get RAG actions' });
  }
});

export default router;
